/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.upf.contatos.rest.integracao;

import br.upf.contatos.dal.model.Contato;
import br.upf.contatos.dal.service.ContatoService;
import br.upf.contatos.rest.integracao.socialapiconect.ContatoImportaLinkedin;
import br.upf.contatos.rest.integracao.socialapiconect.ContatoImportaGmail;
import br.upf.contatos.rest.integracao.socialapiconect.ContatoImportaFacebook;
import br.upf.contatos.rest.integracao.socialapiconect.ContatoImportaTwitter;
import br.upf.contatos.rest.integracao.socialapiconect.ContatoImportaYahoo;
import java.awt.Desktop;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jonas
 */
public class FormularioDeImportacaoDeContatos extends javax.swing.JFrame {

    ContatoImportaYahoo importarYahoo = new ContatoImportaYahoo();
    ContatoImportaTwitter importarTwitter = new ContatoImportaTwitter();
    ContatoImportaGmail importarGmail = new ContatoImportaGmail();
    ContatoImportaLinkedin importarLinkedin = new ContatoImportaLinkedin();
    ContatoImportaFacebook importarFacebook = new ContatoImportaFacebook();
    FormularioDeEdicaoDeContatos form2 = new FormularioDeEdicaoDeContatos();
    Integer redeSocialSetada = -1;
    List<Contato> contatos = new ArrayList();
    ContatoService service = new ContatoService();
            
    /**
     * Creates new form FormularioDeImportacaoDeContatosDoYahoo
     */
    public FormularioDeImportacaoDeContatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 310));
        setSize(new java.awt.Dimension(800, 250));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Importação de contatos do Yahoo para sua lista de contatos. Preencha com seu login e senha e aceite as condições.");

        jButton1.setText("Importar Contatos");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel2.setText("Digite o código de acesso:");

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList1);

        jButton2.setText("Fazer login no Yahoo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Fazer login no Twitter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Fazer login no Gmail");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Editar Selecionado");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Fazer login no Linkedin");
        jButton6.setEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Fazer login no Facebook");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Fazer login no Outlook");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Excluir Selecionado");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Inserir Contato");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jButton9))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.form2.form1 = this;
        try{
            this.contatos.addAll(service.getAll());
            jList1.setListData(getIdNomeEmail().toArray());
        }catch(RuntimeException e){
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        List<Contato> contacts = new ArrayList<>();
        switch (redeSocialSetada){
            case 1: 
                importarYahoo.secondaryYahooConnection(jTextField1.getText());
                importarYahoo.tratamentoYahooResposta();
                contacts.addAll(importarYahoo.getContatos());
                break;
            case 2: 
                importarTwitter.secondaryTwitterConnection(jTextField1.getText());
                importarTwitter.tratamentoTwitterResposta();
                contacts.addAll(importarTwitter.getContatos());
                break;
            case 3: 
                importarGmail.secondaryGmailConnection(jTextField1.getText());
                importarGmail.tratamentoGmailResposta();
                contacts.addAll(importarGmail.getContatos());
                break;
            case 4: 
                importarLinkedin.secondaryLinkedinConnection(jTextField1.getText());
                importarLinkedin.tratamentoLinkedinResposta();
                contacts.addAll(importarLinkedin.getContatos());
                break;
            case 5: 
                importarFacebook.secondaryFacebookConnection(jTextField1.getText());
                importarFacebook.tratamentoFacebookResposta();
                contacts.addAll(importarFacebook.getContatos());
                break;
        }
        contacts.removeAll(this.contatos);
        String mensagem = "";
        for(Contato contato:contacts){
            try{
                service.add(contato);
                this.contatos.add(contato);
            }catch(RuntimeException e){
                mensagem += "Nome: " + contato.getNome() + "  Email: " + contato.getEmail() + "\n";
            }
        }
        if(mensagem.equals("")){
            mensagem = "Todos os contatos foram inseridos com sucesso!";
        }else{
            mensagem = "Alguns contatos não puderam ser inseridos:\n" + mensagem;
        }
        JOptionPane.showMessageDialog(rootPane, mensagem);
        jList1.setListData(getIdNomeEmail().toArray());
        jTextField1.setText("");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        redeSocialSetada = 1;
        importarYahoo.initialYahooConnection();
        try {
            Desktop.getDesktop().browse(new URL(importarYahoo.getAuthURL()).toURI());
        } catch (MalformedURLException ex) {
            Logger.getLogger(FormularioDeImportacaoDeContatos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(FormularioDeImportacaoDeContatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        redeSocialSetada = 2;
        importarTwitter.initialTwitterConnection();
        try {
            Desktop.getDesktop().browse(new URL(importarTwitter.getAuthURL()).toURI());
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(FormularioDeImportacaoDeContatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        redeSocialSetada = 3;
        importarGmail.initialGmailConnection();
        try {
            Desktop.getDesktop().browse(new URL(importarGmail.getAuthURL()).toURI());
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(FormularioDeImportacaoDeContatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //editar contatos
        if(jList1.isSelectionEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Selecione algum contato para ser editado!");
        }else{
            Contato c = this.contatos.get(jList1.getSelectedIndex());
            Contato cont = new Contato();
            cont.setId(c.getId());
            cont.setCep(c.getCep());
            cont.setCidade(c.getCidade());
            cont.setComplemento(c.getComplemento());
            cont.setEmail(c.getEmail());
            cont.setEmailAlternativo(c.getEmailAlternativo());
            cont.setEndereco(c.getEndereco());
            cont.setEstado(c.getEstado());
            cont.setNome(c.getNome());
            form2.contato = cont;
            form2.operacao = 1;
            form2.pos = jList1.getSelectedIndex();
            form2.carregar();
            form2.setVisible(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        redeSocialSetada = 4;
        importarLinkedin.initialLinkedinConnection();
        try {
            Desktop.getDesktop().browse(new URL(importarLinkedin.getAuthURL()).toURI());
        }  catch (MalformedURLException ex) {
            Logger.getLogger(FormularioDeImportacaoDeContatos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(FormularioDeImportacaoDeContatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        redeSocialSetada = 5;
        importarFacebook.initialFacebookConnection();
        try {
            Desktop.getDesktop().browse(new URL(importarFacebook.getAuthURL()).toURI());
        } catch (MalformedURLException ex) {
            Logger.getLogger(FormularioDeImportacaoDeContatos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(FormularioDeImportacaoDeContatos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //excluir contato
        if(jList1.isSelectionEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Nenhum contato selecionado. Selecione algum contato para ser excluido!");
        }else{
            try{
                Integer selected = jList1.getSelectedIndex();
                service.delete(this.contatos.get(selected).getId());
                this.contatos.remove(this.contatos.get(selected));
            }catch(RuntimeException e){
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
        }
        jList1.setListData(getIdNomeEmail().toArray());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        //inserir contato
        Contato contato = new Contato();
        contato.setCep(-1);
        contato.setCidade("");
        contato.setComplemento("");
        contato.setEmail("");
        contato.setEmailAlternativo("");
        contato.setEndereco("");
        contato.setEstado("");
        contato.setId(-1);
        contato.setNome("");
        form2.contato = contato;
        form2.operacao = 0;
        form2.carregar();
        form2.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioDeImportacaoDeContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioDeImportacaoDeContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioDeImportacaoDeContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioDeImportacaoDeContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioDeImportacaoDeContatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public void atualizar() {
        String mensagem = "";
        if(form2.operacao == 0){//inserir
            if(nulo()){//não inseriu nada
                mensagem = "Nenhum contato foi inserido!";
            }else{//inseriu
                try{
                    service.add(form2.contato);
                    contatos.add(form2.contato);
                    form2.contato = null;
                    mensagem = "Contato inserido com sucesso";
                }catch(RuntimeException e){
                    mensagem = e.getMessage();
                }
            }
        }
        if(form2.operacao == 1){//alterar
            if(nulo() || naoModificou()){//não alterou
                mensagem = "Nenhum contato foi alterado!";
            }else{
                try{
                    new ContatoService().update(form2.contato);
                    contatos.set(form2.pos,form2.contato);
                    form2.contato = null;
                    mensagem = "Contato alterado com sucesso!";
                }catch(RuntimeException e){
                    mensagem = e.getMessage();
                }
            }
        }
        JOptionPane.showMessageDialog(rootPane, mensagem);
        jList1.setListData(getIdNomeEmail().toArray());
    }
    
    private boolean nulo(){
        return form2.contato.getNome().equals("") &&
               form2.contato.getEmail().equals("") &&
               form2.contato.getEndereco().equals("") &&
               form2.contato.getComplemento().equals("") &&
               form2.contato.getCep().equals(-1) &&
               form2.contato.getCidade().equals("") &&
               form2.contato.getEstado().equals("") &&
               form2.contato.getEmailAlternativo().equals("");
    }
    
    private boolean naoModificou(){
        Contato cont = this.contatos.get(form2.pos);
        return cont.getNome().equals(form2.contato.getNome()) &&
               cont.getEmail().equals(form2.contato.getEmail()) &&
               cont.getEndereco().equals(form2.contato.getEndereco()) &&
               cont.getComplemento().equals(form2.contato.getComplemento()) &&
               cont.getCep().equals(form2.contato.getCep()) &&
               cont.getCidade().equals(form2.contato.getCidade()) &&
               cont.getEstado().equals(form2.contato.getEstado()) &&
               cont.getEmailAlternativo().equals(form2.contato.getEmailAlternativo());
    }
    
    private List<String> getIdNomeEmail(){
        List<String> resposta = new ArrayList<>();
        for(Contato cont:this.contatos){
            resposta.add(String.format("%s  %s", cont.getId(), cont.getNome().equals("") ? "Sem nome" : cont.getNome()));
        }
        return resposta;
    }
}
