/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.principal;


import com.service.Contato;
import com.service.Retorno;
import com.service.ServidorSoap_Service;
import dao.service;
import java.awt.Dimension;
import java.awt.Toolkit;
import javafx.stage.Screen;
import javax.swing.JOptionPane;
import javax.xml.ws.Service;

/**
 *
 * @author joaov
 */
public class cadastrarContato extends javax.swing.JInternalFrame {

    /**
     * Creates new form cadastrarContato
     */
    public cadastrarContato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoEmailAlter = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoCidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoComplemento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        campoEstado = new javax.swing.JComboBox<>();
        campoCep = new javax.swing.JTextField();
        campoCodigo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setClosable(true);
        setTitle("Adicionar Contato");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 50, -1, -1));
        getContentPane().add(campoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 45, 285, -1));
        getContentPane().add(campoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 78, 285, -1));

        jLabel2.setText("Email:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 83, -1, -1));
        getContentPane().add(campoEmailAlter, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 111, 285, -1));

        jLabel3.setText("Email Alter:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 116, -1, -1));

        jLabel4.setText("Cep:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 149, -1, -1));

        jLabel5.setText("Estado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 182, -1, -1));
        getContentPane().add(campoCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 210, 285, -1));

        jLabel6.setText("Cidade:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 215, -1, -1));
        getContentPane().add(campoEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 243, 285, -1));

        jLabel7.setText("Endereço:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 248, -1, -1));
        getContentPane().add(campoComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 276, 285, -1));

        jLabel8.setText("Complemento:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 281, -1, -1));

        jButton1.setText("Inserir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 315, -1, -1));

        campoEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum Estado Selecionado", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        getContentPane().add(campoEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 177, 187, -1));
        getContentPane().add(campoCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 144, 129, -1));
        getContentPane().add(campoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 12, 96, -1));

        jLabel9.setText("Código");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 17, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Contato c = new Contato();
       c.setCodigo(Integer.parseInt(campoCodigo.getText()));
       c.setCep(Integer.parseInt(campoCep.getText()));
       c.setNome(campoNome.getText());
       c.setEmail(campoEmail.getText());
       c.setEmailAlter(campoEmailAlter.getText());
       c.setEndereco(campoEndereco.getText());
       c.setEstado((String) campoEstado.getSelectedItem());
       c.setCidade(campoCidade.getText());
       c.setComplemento(campoComplemento.getText());
       
        Retorno retorno   = dao.insert(c);
        
        int erro = retorno.getCodigo();
        
        c = retorno.getContato();
        
        if(erro == 1){
            JOptionPane.showMessageDialog(this, "Erro ao inserir o contato. Por Favor tente Novamente!");
        }
        
        if(erro == 2){
            JOptionPane.showMessageDialog(this, "Contato "+c.getNome()+" Inserido com Sucesso!");
            campoCep.setText("");
            campoCodigo.setText("");
            campoCidade.setText("");
            campoComplemento.setText("");
            campoEmail.setText("");
            campoEmailAlter.setText("");
            campoEndereco.setText("");
            campoEstado.setSelectedItem("");
            campoNome.setText("");
            campoCodigo.requestFocus();           
            
            int r = JOptionPane.showConfirmDialog(campoComplemento, "Deseja Inserir um novo Contato ?");
            System.out.println(r);
        }
        
        
       
       
        //JOptionPane.showMessageDialog(this, retorno.getCodigo() + retorno.getMsg());
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        //jinical.setSize(screenSize.width, screenSize.height);        
        controleTelas.getJdesk().removeAll();
        controleTelas.getJdesk().add(jinical);
        controleTelas.getJdesk().repaint();
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoCep;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoComplemento;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoEmailAlter;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JComboBox<String> campoEstado;
    private javax.swing.JTextField campoNome;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
service dao = new service();
 janelaInicial jinical = new janelaInicial();
  Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
}
