/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.principal;


import dao.service;
import com.service.Contato;
import com.service.Retorno;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author joaov
 */
public class janelaInicial extends javax.swing.JInternalFrame {

    /**
     * Creates new form inicial
     */
    public janelaInicial() {
        initComponents();
        
         List<Contato> listaDao = dao.getAll();
         list.addAll(listaDao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        list = org.jdesktop.observablecollections.ObservableCollections.observableList(new ArrayList<Contato>())
        ;
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        campoEmailAlter = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoCódigo = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        CampoEmail = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        campoCep = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoCidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoComplemento = new javax.swing.JTextField();
        campoEstado = new javax.swing.JComboBox<>();
        botaoAPagar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        campoBusca = new javax.swing.JTextField();
        botaoConsultar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        campoBuscaCidade = new javax.swing.JTextField();
        botaoConsultarCidade = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        botaoAtualizar = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(1));
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Lista de Contatos");
        setFocusCycleRoot(false);
        setRequestFocusEnabled(false);
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabela.setAutoCreateRowSorter(true);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, tabela);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codigo}"));
        columnBinding.setColumnName("Codigo");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${email}"));
        columnBinding.setColumnName("Email");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${emailAlter}"));
        columnBinding.setColumnName("Email Alter");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cep}"));
        columnBinding.setColumnName("Cep");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${estado}"));
        columnBinding.setColumnName("Estado");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cidade}"));
        columnBinding.setColumnName("Cidade");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${endereco}"));
        columnBinding.setColumnName("Endereco");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${complemento}"));
        columnBinding.setColumnName("Complemento");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 103, 806, 239));

        jLabel4.setText("Email Secundário:");

        jLabel1.setText("Código:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Email:");

        campoCódigo.setEditable(false);
        campoCódigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCódigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCódigo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoEmailAlter, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoCódigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoEmailAlter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 354, -1, -1));

        jLabel9.setText("Complemeno");

        jLabel5.setText("Cep");

        jLabel6.setText("Estado:");

        jLabel7.setText("Cidade");

        jLabel8.setText("Endereço");

        campoEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Nenhum Estado Selecionado", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        campoEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoCep, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campoComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 354, -1, -1));

        botaoAPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgens/del.png"))); // NOI18N
        botaoAPagar.setText("Apagar");
        botaoAPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAPagarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoAPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 531, -1, -1));

        jLabel10.setText("Email ou Id do Contato que deseja Buscar:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 17, -1, -1));

        campoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscaActionPerformed(evt);
            }
        });
        getContentPane().add(campoBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 12, 170, -1));

        botaoConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgens/identifcation.png"))); // NOI18N
        botaoConsultar.setText("Consultar");
        botaoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 3, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgens/all.png"))); // NOI18N
        jButton1.setText("Buscar Todos Contatos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 3, -1, -1));

        campoBuscaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscaCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(campoBuscaCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 62, 170, -1));

        botaoConsultarCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgens/city.png"))); // NOI18N
        botaoConsultarCidade.setText("Consultar");
        botaoConsultarCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsultarCidadeActionPerformed(evt);
            }
        });
        getContentPane().add(botaoConsultarCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 53, -1, -1));

        jLabel11.setText("Buscar Contatos da Cidade:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 67, 287, -1));

        botaoAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgens/refresh.png"))); // NOI18N
        botaoAtualizar.setText("Atualizar");
        botaoAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoAtualizarMouseClicked(evt);
            }
        });
        getContentPane().add(botaoAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 531, -1, -1));

        getAccessibleContext().setAccessibleDescription("");

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        Contato c = list.get(tabela.getSelectedRow());
        if(c.getEstado().equals("")){
            c.setEstado("Nenhum Estado Selecionado");
        }
        
        c.setEstado(c.getEstado().toUpperCase());        
        
        campoCódigo.setText(Integer.toString(c.getCodigo()));
        campoNome.setText(c.getNome());
        CampoEmail.setText(c.getEmail());
        System.out.println(c.getEstado());
        
        if(c.getEmailAlter()== null){
            campoEmailAlter.setText("");
        }else{            
            campoEmailAlter.setText(c.getEmailAlter());
        }
        
        if(c.getCep() == null){
            campoCep.setText("");
        }else{
            campoCep.setText(Integer.toString(c.getCep()));
           
        }
        
        if(c.getCidade()== null){
            campoCidade.setText("");
        }else{
            campoCidade.setText(c.getCidade());
            
        }
        
        if(c.getEndereco()== null){
            campoEndereco.setText("");
        }else{
            campoEndereco.setText(c.getEndereco());
            
        }
        
        if(c.getEstado() == null || c.getEstado() == ""){
            campoEstado.setSelectedItem("Nenhum Estado Selecionado");          
        }else{
            campoEstado.setSelectedItem(c.getEstado());
        }
        
        if(c.getComplemento()== null){
            campoComplemento.setText("");
        }else{
            campoComplemento.setText(c.getComplemento());
            
        }       
        
    }//GEN-LAST:event_tabelaMouseClicked

    private void campoEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEstadoActionPerformed

    private void botaoAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAPagarActionPerformed
        Contato c = list.get(tabela.getSelectedRow());
        Retorno retorno = new Retorno();
        
        int input = JOptionPane.showConfirmDialog(campoComplemento, "Deseja realmente Apagar o contato: " + c.getNome());
        if(input == 0){
            retorno = dao.delete(c.getCodigo());       
        }
        
        try {
            AtualizaTabela(evt);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(janelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(retorno.getCodigo() == 2){
            JOptionPane.showMessageDialog(campoComplemento, "O Contato " + c.getNome() + " foi apagado com sucesso!!!");
        }
        if(retorno.getCodigo() == 1){
            JOptionPane.showMessageDialog(campoComplemento, retorno.getMsg());
        }
    }//GEN-LAST:event_botaoAPagarActionPerformed

    private void campoCódigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCódigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCódigoActionPerformed

    private void botaoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarActionPerformed
        String busca = campoBusca.getText();
        Retorno retorno = new Retorno();
        
        boolean r = busca.matches("[-+]?\\d*\\.?\\d+");
        
        if(r == true){
            retorno = dao.getById(Integer.parseInt(busca));
            list.clear();
            list.add(retorno.getContato());
        }else{
            retorno = dao.getByEmail(busca);
            
            if(retorno.getCodigo() == 3){
                JOptionPane.showMessageDialog(this, "Nenhum Contato foi Encontrado");
            }else{            
                list.clear();
                list.addAll(retorno.getLista());
            }
            
        }   
        
        
        
        
        
        
        
    }//GEN-LAST:event_botaoConsultarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<Contato> listaDao = dao.getAll();
        list.clear();
        list.addAll(listaDao);
        campoBusca.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscaActionPerformed

    private void botaoConsultarCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsultarCidadeActionPerformed
        if(campoBuscaCidade.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo Cidade !");
            campoBuscaCidade.requestFocus();
            return;
        }
            
            String busca = campoBuscaCidade.getText();
            Retorno retorno = new Retorno();

            retorno = dao.getByCidade(busca);

            //erro
            if(retorno.getCodigo() == 3){
                JOptionPane.showMessageDialog(this, "Nenhum contato está vinculado a cidade: "+busca);
            }else{            
                list.clear();
                list.addAll(retorno.getLista());
            }
        
    }//GEN-LAST:event_botaoConsultarCidadeActionPerformed

    private void campoBuscaCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscaCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscaCidadeActionPerformed

    private void botaoAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAtualizarMouseClicked
        Contato tab = list.get(tabela.getSelectedRow());        
        Contato c = new Contato();
        
        c.setNome(campoNome.getText());
        c.setEstado(campoEstado.getSelectedItem().toString());
        c.setEndereco(CampoEmail.getText());
        c.setEmailAlter(campoEmailAlter.getText());
        c.setEmail(CampoEmail.getText());
        c.setCodigo(Integer.parseInt(campoCódigo.getText()));
        c.setCidade(campoCidade.getText());
        c.setCep(Integer.parseInt(campoCep.getText()));
        
        if(tab.getClass() == c.getClass()){
            JOptionPane.showInternalMessageDialog(controleTelas.getJdesk(), "Altere pelo menos algum dado do Cliente");
        }else{
            JOptionPane.showInternalMessageDialog(controleTelas.getJdesk(), "atualizando . . ");
        }
    }//GEN-LAST:event_botaoAtualizarMouseClicked

    private void AtualizaTabela(ActionEvent evt) throws ClassNotFoundException {
         List<Contato> listaDao = dao.getAll();
         list.clear();
         list.addAll(listaDao);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoEmail;
    private javax.swing.JButton botaoAPagar;
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoConsultar;
    private javax.swing.JButton botaoConsultarCidade;
    private javax.swing.JTextField campoBusca;
    private javax.swing.JTextField campoBuscaCidade;
    private javax.swing.JTextField campoCep;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoComplemento;
    private javax.swing.JTextField campoCódigo;
    private javax.swing.JTextField campoEmailAlter;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JComboBox<String> campoEstado;
    private javax.swing.JTextField campoNome;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.util.List<Contato> list;
    private javax.swing.JTable tabela;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
service dao = new service();
}
